version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fast-api-playground
      POSTGRES_USER: fast-api-playground
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: uvicorn fast_api_playground.main:app --reload --host "0.0.0.0" --port 8020
    volumes:
      - .:/code
    ports:
      - "8020:8020"
    depends_on:
      - db
